/* eslint-disable no-console */
import { showLogger } from "@/constant/env";

/**
 * A logger function that will only logs on development
 * @param object - The object to log
 * @param comment - Autogenerated with `lg` snippet
 */
export default function logger(object: unknown, comment?: string): void {
  if (!showLogger) return;

  console.log(
    `%c============= INFO LOG =============\n%cPath: ${window?.location.pathname}\n%cMessage: ${comment ?? ""}\n%cObject:`,
    "color: #22D3EE; font-weight: bold;",
    "color: #10B981;",
    "color: #FBBF24;",
    "color: #E879F9;",
    object
  );
}
